
services:
  backend_service:
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
    depends_on:
      - postgres_service
    restart: always

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=stickify_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5434:5432"

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "8001:8001"
      - "443:443"
    depends_on:
      - backend_service

volumes:
  static_volume:
