
services:
  backend_service:
    build: .
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - static_volume:/app/static
    command: uv run python3 manage.py runserver 0.0.0.0:8001
    depends_on:
      - postgres_service
    restart: always

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=stickify_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5434:5432"

volumes:
  static_volume: