services:
  backend_service:
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
    depends_on:
      - postgres_service
    restart: always

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=stickify_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend_service

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: /bin/sh

volumes:
  static_volume:
  pg_data:
  certbot-etc:
  certbot-var:
